name: Cypress Docker Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build Docker image
      run: docker build -t my-cypress-image .

    - name: Run Cypress in Docker
      run: docker run -e CYPRESS_baseUrl=http://localhost \
                      -e CYPRESS_user_name=${{ secrets.USER_NAME }} \
                      -e CYPRESS_user_password=${{ secrets.USER_PASSWORD }} \
                      -e CYPRESS_gitlab_access_token=${{ secrets.GITLAB_ACCESS_TOKEN }} \
                      my-cypress-image
